<?php

/*
 * Implements hook_views_api
 */

function jit_views_views_api(){
    return array('api'=>3,);
}

function jit_views_views_data() {
  $data = array();

  $data['jit_settings_sections']['table']['group'] = t('JIT Products Sections');

  $data['jit_settings_sections']['table']['base'] = array(
    'field' => 'jid',
    'title' => t('JIT Product Sections'),
    'help' => t('This table contains the accordian section codes for the JIT Products module'),

  );

  $data['jit_settings_sections']['jid'] = array(
    'title' => t('Unique identifier'),
    'help' => t('Primary Key of the section record'),
    'field' => array(
        'handler' => 'views_handler_field',
    ),
    'sort' => array(
        'handler' => 'views_handler_sort_numeric',
    ),
    'filter' => array(
        'handler' => 'views_handler_filter_numeric',
    ),
  );

  $data['jit_settings_sections']['section_name'] = array(
    'title' => t('Section Name'),
    'help' => t('The Section Name'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['jit_settings_sections']['section_code'] = array(
    'title' => t('Section Code'),
    'help' => t('The Code for the Section'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['jit_settings_sections']['panel_name'] = array(
    'title' => t('Panel Name'),
    'help' => t('The name of the Panel that the Section is in'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  // Example numeric text field.
  $data ['jit_settings_sections']['weight'] = array(
    'title' => t('Weight'),
    'help' => t('The weight of the section in its panel'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  $data['jit_settings_sections']['modifiedby'] = array(
    'title' => t('Section Last Modified By'),
    'help' => t('Shows the User ID of the Last Person that Modified this Record'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );


  $data['jit_settings_sections']['modifieddate'] = array(
    'title' => t('Section Last Modified Date'),
    'help' => t('Date and Time stamp of the last time this record was modified'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort_date',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_date',
    ),
  );

  return $data;
}



